
title: Dogetoreum Whitepaper
description: Official Dogetoreum Whitepaper showcasing the core vision and technical aspects of the blockchain.
theme: minima
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # Your GitHub Pages URL
