
title: Dogetoreum
description: Official Dogetoreum Website showcasing the core vision and technical aspects of the blockchain.
theme: minima
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://DogeToreum/dogtoreum.github.io" # Your GitHub Pages URL
